openapi: 3.0.0
info:
    title: Locations
    version: 1.0.0
    description: Locations API
paths:
    /locations:
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/location'
components:
    schemas:
        location:
            title: Root Type for location
            description: The root of the location type's schema.
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                location:
                    type: object
                    properties:
                        lat:
                            format: double
                            type: number
                        long:
                            format: double
                            type: number
                type:
                    type: string
                status:
                    format: int32
                    type: integer
